[2017-09-08 09:48:31] Test message
[2017-09-08 09:48:45] Test message
[2017-09-08 09:48:45] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 12:25:24] Test message
[2017-09-11 12:25:24] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 12:25:50] Test message
[2017-09-11 12:25:50] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 12:28:59] Test message
[2017-09-11 12:28:59] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 12:35:48] Test message
[2017-09-11 12:35:48] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 12:36:16] Test message
[2017-09-11 12:36:16] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 12:36:46] Test message
[2017-09-11 12:36:46] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 12:41:06] Test message
[2017-09-11 12:41:06] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 12:41:40] Test message
[2017-09-11 12:41:40] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 12:43:41] Test message
[2017-09-11 12:43:41] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 12:45:03] Test message
[2017-09-11 12:45:03] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 12:45:22] Test message
[2017-09-11 12:45:22] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 12:55:39] Test message
[2017-09-11 12:55:39] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 12:56:50] Test message
[2017-09-11 12:56:50] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 12:59:58] Test message
[2017-09-11 12:59:58] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 13:16:50] Test message
[2017-09-11 13:16:50] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 13:17:06] Test message
[2017-09-11 13:17:06] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 13:31:37] Test message
[2017-09-11 13:31:37] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 13:33:35] Test message
[2017-09-11 13:33:35] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 13:34:32] Test message
[2017-09-11 13:34:32] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 13:34:52] Test message
[2017-09-11 13:34:52] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 13:35:26] Test message
[2017-09-11 13:35:26] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 13:38:24] Test message
[2017-09-11 13:38:24] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 13:38:39] Test message
[2017-09-11 13:38:39] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 13:39:46] Test message
[2017-09-11 13:39:46] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 13:40:46] Test message
[2017-09-11 13:40:46] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 13:44:21] Test message
[2017-09-11 13:44:21] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 13:47:17] Test message
[2017-09-11 13:47:17] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
[2017-09-11 13:47:59] Test message
[2017-09-11 13:47:59] PHPUnit\Runner\Exception: Test exception in /home/laptop02/theShop/VagrantLAMP/Sites/framework/Modules/RestApi/test/Logger/FileLoggerTest.php:32
Stack trace:
#0 [internal function]: Framework\RestApiTest\Logger\FileLoggerTest->testFileLoggerExceptionMessage()
#1 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(1069): ReflectionMethod->invokeArgs(Object(Framework\RestApiTest\Logger\FileLoggerTest), Array)
#2 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(928): PHPUnit\Framework\TestCase->runTest()
#3 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestResult.php(695): PHPUnit\Framework\TestCase->runBare()
#4 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Framework\RestApiTest\Logger\FileLoggerTest))
#5 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#6 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#9 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#10 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#11 /home/laptop02/theShop/VagrantLAMP/Sites/framework/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#12 {main}
